export const UPDATE_FILM_ADMIN_REQUSET = '@@updatefilm/UPDATE_FILM_ADMIN_REQUSET';
export const UPDATE_FILM_ADMIN_SUCCESS = '@@updatefilm/UPDATE_FILM_ADMIN_SUCCESS';
export const UPDATE_FILM_ADMIN_FAIL = '@@updatefilm/UPDATE_FILM_ADMIN_FAIL';