export const EDIT_FILM_ADMIN_REQUSET = '@@editfilm/EDIT_FILM_ADMIN_REQUSET';
export const EDIT_FILM_ADMIN_SUCCESS = '@@editfilm/EDIT_FILM_ADMIN_SUCCESS';
export const EDIT_FILM_ADMIN_FAIL = '@@editfilm/EDIT_FILM_ADMIN_FAIL';