export const DASHBOARD_REQUSET = '@@addfilm/DASHBOARD_REQUSET';
export const DASHBOARD_SUCCESS = '@@addfilm/DASHBOARD_SUCCESS';
export const DASHBOARD_FAIL = '@@addfilm/DASHBOARD_FAIL';
export const DELETE_FILM_DASHBOARD_REQUEST = '@@addfilm/DELETE_FILM_DASHBOARD_REQUEST';
export const DELETE_FILM_DASHBOARD_SUCCESS = '@@addfilm/DELETE_FILM_DASHBOARD_SUCCESS';
export const DELETE_FILM_DASHBOARD_FAIL = '@@addfilm/DELETE_FILM_DASHBOARD_FAIL';
export const SEARCH_FILM_DASHBOARD_FAIL = '@@addfilm/SEARCH_FILM_DASHBOARD_FAIL';
