export const ADD_USER_ADMIN_REQUSET = '@@adduser/ADD_USER_ADMIN_REQUSET';
export const ADD_USER_ADMIN_SUCCESS = '@@adduser/ADD_USER_ADMIN_SUCCESS';
export const ADD_USER_ADMIN_FAIL = '@@adduser/ADD_USER_ADMIN_FAIL';