export const GET_HE_THONG_RAP_REQUEST = '@@showtime/GET_HE_THONG_RAP_REQUEST';
export const GET_HE_THONG_RAP_SUCCESS = '@@showtime/GET_HE_THONG_RAP_SUCCESS';
export const GET_HE_THONG_RAP_FAIL = '@@showtime/GET_HE_THONG_RAP_FAIL';

export const GET_CUM_RAP_THEO_HE_THONG_REQUEST = '@@showtime/GET_CUM_RAP_THEO_HE_THONG_REQUEST';
export const GET_CUM_RAP_THEO_HE_THONG_SUCCESS = '@@showtime/GET_CUM_RAP_THEO_HE_THONG_SUCCESS';
export const GET_CUM_RAP_THEO_HE_THONG_FAIL = '@@showtime/GET_CUM_RAP_THEO_HE_THONG_FAIL';

export const POST_TAO_LICH_CHIEU_REQUEST = '@@showtime/POST_TAO_LICH_CHIEU_REQUEST';
export const POST_TAO_LICH_CHIEU_SUCCESS = '@@showtime/POST_TAO_LICH_CHIEU_SUCCESS';
export const POST_TAO_LICH_CHIEU_FAIL = '@@showtime/POST_TAO_LICH_CHIEU_FAIL';